blob.server.port: 6124
execution.checkpointing.mode: EXACTLY_ONCE
taskmanager.memory.process.size: 1728m
classloader.check-leaked-classloader: false
jobmanager.rpc.address: jobmanager
jobmanager.memory.process.size: 1600m
state.savepoints.dir: s3://flink-savepoints/savepoints
jobmanager.rpc.port: 6123
query.server.port: 6125
rest.bind-address: 0.0.0.0
fs.overwrite-files: true
rest.port: 8081
execution.checkpointing.interval: 30s
s3.access-key: minio
s3.connection.ssl.enabled: false
s3.secret-key: minio123
s3.endpoint: http://minio:9000
execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION
parallelism.default: 2
taskmanager.numberOfTaskSlots: 2
rest.address: jobmanager
state.checkpoints.dir: s3://flink-checkpoints/checkpoints
s3.path.style.access: true
